### ISSUE TITLE
Official support for Raspbian Jessie

### ISSUE THREAD

**Issue by joolswills** [RetroPie/RetroPie-Setup#1029]
Jessie is now released on the raspberrypi.org site. Need to build and test new images based on Jessie and build binaries for Jessie also.

https://www.raspberrypi.org/blog/raspbian-jessie-is-here/

**Comment by pancakeykakes** [comment]
So far I am not impressed with Jessie. Based on what I read, that is.

**Comment by joolswills** [comment]
Please do share any links you think would be useful. We don't include desktop components in our prebuilt images, but we would benefit from updated versions of some userland components.

**Comment by HerbFargus** [comment]
So is it your intention to have 3.1 be based on Raspbian Jessie- or is this for future releases that you're looking at? I'm happy to give any new images a test

**Comment by joolswills** [comment]
An undecided future release.. some time after 3.1

**Comment by pancakeykakes** [comment]
How do you guys feel about making a standalone version for Jessie? That would make me a bit more tempted to try it out. I run Wheezy with Kodi and RetroPie on top of it as standalone environments.

Another thing is if you guys do plan on that, I will be able to update my TriPi script for controller navigation into it for any of my users that want to upgrade.

**Comment by joolswills** [comment]
At some point I guess there will be a Jessie based image for testing as well as the standard version, but I am not going to build 2 sets of images for every release.

**Comment by pancakeykakes** [comment]
Fair enough.

**Comment by lukeroge** [comment]
Another +1 for Jessie support. I moved my multi-use project to Jessie to get newer python versions, and official support for on-the-side emulation would be nice.

**Comment by joolswills** [comment]
Note you can install it manually on Jessie now - just no binary installs available, but if you wanted to build some emulators from source that should all work.

**Comment by lukeroge** [comment]
I had some bizarre issues installing emulationstation, but I think it might just be my image corrupting. Apt kept locking up on installing libboost, despite trying all kinds of dpkg and aptitide tricks. Oh well! I'll update my post after a reimage.

**Comment by diogomsantos** [comment]
I just tried making a source based instalattion in a clean official Raspbian Jessie Image and the first error I got is building SDL1. Here is the log:
http://pastebin.com/Uf4g1VuJ

Now it started compiling the emulators and will let it finish, meanwhile if I found another error I will paste it here.

**Comment by joolswills** [comment]
thanks will check/debug - this is new - I guess they added a prepatched rpi sdl to jessie now that it's officially released (rpi foundation are using our exiting patchsets, so I need to check for that).

**Comment by joolswills** [comment]
or just forcing a vanilla debian sdl would be fine. We could just accept the raspbian sdl as it's already got our fixes in, but we might add new stuff later (perhaps).

**Comment by diogomsantos** [comment]
Ok, I already had SDL 1.2.15-10 and SDL 2.0.2 installed from the Raspbian repo, but wasn't sure that will work. 
Everything seemed to compilied fine including SDL2, unless lr-mednafen-wsan and lr-mednafen-ngp which failed because /home/pi/RetroPie/tmp/build/$emulator/README.md not found in both.

Will test now ES and some emulators to check if they are working.

**Comment by joolswills** [comment]
Sounds like you need to update retropie-setup - lr-mednafen-wsan and lr-mednafen-ngp were fixed up a week ago.

**Comment by joolswills** [comment]
5 days not a week. sorry.

**Comment by joolswills** [comment]
Please can you post me more of the log from earlier - It's not complete and I need to see the source stage of the sdl1 build/fail (As It worked here)

**Comment by joolswills** [comment]
I can probably reproduce it from a fresh image, but will save me time - I'm assuming there is a difference between our deb-src apt sources. Downloading a vanilla Raspbian jessie image now anyway to see.

**Comment by joolswills** [comment]
should be fixed now.

**Comment by diogomsantos** [comment]
Yes I had Raspbian Jessie installed about a week ago and cloned RetroPie-Setup +/- at the same time but only now I had the opportunity to lay hands on that. Updating RetroPie-Setup fixed ngp and wswan.

The old log was corrupted (sometimes logs get corrupted, don't know why but that already happens in Wheezy). Anyway here is a new one:
http://pastebin.com/cms63qMP

Another thing I noticed that doesn't work is the splashscreen. I tried multiple, the sysvinit script is processed but nothing happens. I believe that's because of systemd. I already tried to make a systemd service for fbi but still not working yet (exits with "Oops Terminated).

**Comment by joolswills** [comment]
I have the splashscreen working ok here on jessie - so not sure what the problem is. I'll try from a fresh image though - you did "enable splashscreen" from the configuration ?

**Comment by joolswills** [comment]
Tested on a fresh Raspbian jessie and it worked fine - did you configure it to boot to "Console Autologin" via raspi-config?

Without that it will boot to a desktop, and the desktop starts loading early enough as to not give the splash a chance to startup.

**Comment by diogomsantos** [comment]
Sorry didn't saw your message about SDL1, it compiles fine now. Splashscreen also working just fine, the problem was that I was using an old custom one, thanks.

Some things I noticed that the source-based installation doesn't install,  don't know if this is expected or not:
-es-theme (none are installed)
-retropie menu
-samba shares  (not sure about this)
-ES autostart

ES (from terminal and autostart enable/disable) is working fine, USB gamepad configuration in ES also, but I didn't test the emulators yet. 

It seems that all RetroPie-Setup scripts are working fine but I didn't test some because I don't have the hardware to test, like:
-wireless/bluetooth gamepads like PS3 and XBOX 360
-xarcade2joystick

RetroPie Menu options are working also.

Maybe it will not be needed much work afterall to get RetroPie working fine in Raspbian Jessie :D

Time to test the emulators with one USB Logitech gamepad.

**Comment by joolswills** [comment]
es-theme - you are installing from source - a default theme is only set up when installing from binaries, but you can just install a theme via the supplementary menu - there is a theme installer. 

retropie menu is expected to be installed manually if using the source install, same for shares, and ES autostart. they are configured from the supplementary menu.

There was plenty of work to get RetroPie-Setup working in Jessie :) - The work was done some weeks ago. This ticket was opened for me to track "official" support - ie, out of the box with binaries and shipping jessie by default.

**Comment by diogomsantos** [comment]
Yes I know that options can be installed from the RetroPie-Setup script, I have done that already.

So maybe the next step is to test the binaries compiled from source, and if they are working, to make binary packages, put them on the RetroPie server and enable the option to Install binaries.

**Comment by joolswills** [comment]
It's already in progress - this was why I opened the ticket for myself :)

**Comment by HerbFargus** [comment]
So will there be two binary options then when updating? One for wheezy and one for Jessie?

**Comment by joolswills** [comment]
Just one. It will know which distro you are on.

**Comment by joolswills** [comment]
I actually built binaries for Jessie a week ago, but then got busy doing the 3.1 release - I'm building them now again though.

**Comment by HerbFargus** [comment]
Just as a reference for others: this is how I installed retropie on raspbian jessie manually (from source):

```
Installing Retropie Manually (from Raspbian Jessie):


INSTALL RASPBIAN:

https://www.raspberrypi.org/downloads/raspbian/

unzip
write to sd card with win32diskimager

sudo raspi-config

boot options
console autologin

expand filesystem
reboot

INSTALL RETROPIE:

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install git

cd
git clone --depth=1 https://github.com/RetroPie/RetroPie-Setup.git

cd RetroPie-Setup
sudo ./retropie-setup

Install Emulationstation

Auto Start Emulationstation

Install Theme from setup script

Enable Samba Shares
(hostname is raspberrypi not RETROPIE)

Install Retroarch

Install your emulators

transfer your roms

reboot
```

**Comment by HerbFargus** [comment]
just ran a full binary install: 

could not install package(s): libxaw7-dev checkinstall.

full log:

http://pastebin.com/8ZhjQ9u6

may have been a network thing again but  not necessarily sure- it all seems to work though, still testing

**Comment by joolswills** [comment]
Your install issue was a network problem. 

Will look into mgba when i get a chance. thanks.

**Comment by HerbFargus** [comment]
yeah lr-mgba issues are specific to jessie as compiling from source on my wheezy build had no issues.

**Comment by joolswills** [comment]
you could try compiling just that emulator from source on jessie - might be my cross compiler.

**Comment by HerbFargus** [comment]
thats the next thing on my list- will report results

**Comment by HerbFargus** [comment]
same issue:

here's the build log:

http://pastebin.com/9ceKhY8C

**Comment by joolswills** [comment]
ok thanks.

**Comment by carlosouro** [comment]
Hi guys,

PS3 Controller Setup is not working in Jessie.
No expert here, but it seems like it's due to how bluetooth support has changed in Jessie.

bluez-utils and other packages no longer exist in Jessie (apt-get says it has been replaced with just bluez), making #includes fail during setup.
Then the ps3 setup screen comes up but fails saying no PS3 USB controller found and it fails all together.

Errors given at the end:

* Could not install: bluez-utils bluez-compat bluez-hcidump libusb-dev libbluetooth-dev joystick libusb-1.0-0-dev
* Could not successfully install (/home/pi/RetroPie-Setup/tmp/build/ps3controller/sixpair not found)
* please see log blah blah (let me know if you really really need it)

**Comment by joolswills** [comment]
Thanks.

**Comment by joolswills** [comment]
ps3controller should be fixed now.

**Comment by joolswills** [comment]
the mgba problem should be fixed. I'm going to build new binaries for wheezy / jessie now.

**Comment by ProxyCell** [comment]
Hi,

Is building from source on Jessie working for anybody? I just ran my first one and it threw a ton of warnings/errors/failures at me. I did try to built a lot of stuff at once and my next run will be a bit easier but I was wondering if you guys had any experience with it already.

**Comment by HerbFargus** [comment]
I installed it manually piece by piece and ran into a few dependency errors but they were fixed for the things i tried. I didn't try a whole lot of things though. I did the partial install explained on this page:

https://github.com/RetroPie/RetroPie-Setup/wiki/Manual-Installation

**Comment by joolswills** [comment]
@ProxyCell without any log I can't advise.

**Comment by joolswills** [comment]
I would add that source builds can break often due to upstream changes. Stuff is fixed as/when I have a chance. Binaries are available for Jessie, so I would use those.

**Comment by ProxyCell** [comment]
@HerbFargus & @joolswills 
Thanks a lot for the replies! I will begin the next run tomorrow and I will do them one by one.

**Comment by jimbo27** [comment]
Hi guys,

after >1 year of using Retriopie an a Pi1 I decided to step over to a Pi2. For a fresh new install I decided on Jessie because of its future compatibility and perhaps better support for Pi2.

I installed Jessie Lite (from https://www.raspberrypi.org/downloads/raspbian/, version November 2015).

Following the hints above I tried to install RetroPie step by step (partial install). I began with git, dialog and then the RetroPie script. After that I tried to install Emulationstation through the RetroPie-Frontend. The binary version failed to install so I tried the source version which installed almost error free (I saw some dependency problems in the log). Anyway: After installing the simple theme Emulationstation started successfully on my Pi2. es_systems.cfg were missing so I had to get an actual version from the internet.

After that I wanted to see my first emulator running on my RetroPie system. I decided on Retroarch and Libretro cores for SNES. I started with Retroarch. This time I could not compile the source version so I installed the binaries. After that I installed two Libretro cores (Pocketsnes and SNES9x and some roms.
Unfortunately Emulationstation could not start the emulator. runcommand.log says:
/opt/retropie/emulators/retroarch/bin/retroarch: error while loading shared libraries: libjack.so.0: cannot open shared object file: No such file or directory

So my installation seems to be broken. Any hint what I did wrong?

PS: I am interested to get this thing working on Jessie. I am no coder but I am ready to help with log files of install attempts of binary or source versions. I am capable of making backups anytime in order to wind back to a previous version of my system. For example I could go back to a clean system without RetroPie. I could try to install every component step by step and post the resulting logfiles. Would this be helpful?

**Comment by HerbFargus** [comment]
RetroArch is currently under a lot of development so its more than likely it will break from source than it will build, so I would stick with binaries for everything (if they were built for jessie) as there really isnt a whole lot of benefit to building from source.  We've been sorting out 3.3 pending RetroArch and holidays and then perhaps we'll focus more on Jessie support. Ideally RetroPie should be modular enough to build from individual pieces but sometimes dependencies slip through (this will be sorted in time) 

As far as what you are doing, if you do have logs you can put them on pastebin and post links for your build logs so we know what broke it. @joolswills I know this isn't top priority right now but for long term do you think it would be worth making a chart on a google sheet or something for each core?

too late already did it anyways- Just a way to organise what builds from source and what doesn't- just for getting started:

https://docs.google.com/spreadsheets/d/17f4qvN33DTjYeuCbbLfVyUEe4WUIKuwEpXKUykGfOBA/edit?usp=sharing

**Comment by joolswills** [comment]
as Herb says - it is not yet production ready on Jessie. I have also never tested on the Jessie Lite, so it will need some more work im sure to work on there out of the box (due to some dependencies we miss - I will need to go through this). 

Not sure the spreadsheet will be of use to me - I prefer just to use the issue tracker etc. If you want to keep a spreadsheet though of course feel free.

If you post a debug log I can advise further (with build issues), but the issue with retroarch binaries is they need rebuilding as they were built with libjack, but we don't include a dependency for it. this is fixed in source though and the next binaries won't include this.

If you just want a working RetroPie, please use an image or start from Wheezy.

**Comment by joolswills** [comment]
you can also install libjack-dev to fix the missing lib for retroarch.

**Comment by joolswills** [comment]
RetroArch doesn't build from source currently on the rpi.

**Comment by jimbo27** [comment]
@joolswills: after installing libjack-dev lr-snes9x-next (binary install) works! great! :+1:
lr-pocketsnes (binary install) still do not work for me. runcommand.log is empty...

Whatever: I will now start with a clean new Jessie Lite and try to install every component from source and binary. I will post my findings to Pastebin and those Pastbin links to the spreadsheet mentioned above. The spreadsheet will help to keep track of progress (thanks @HerbFargus )

**Comment by joolswills** [comment]
Please can you wait until I have had a chance to go through it with Jessie lite - it will be easier for me to fix up anything obvious that way.

**Comment by jimbo27** [comment]
Sure. No problem.

**Comment by joolswills** [comment]
So the Jessie image is released. Everything has been tested - sorry I forgot to get back to you @jimbo27 - I went through everything and it looks like all the binaries are working ok. Feel free to do your own testing however.

I've not heard any Jessie specific bug reports yet, so I may well make it the official image for the next release so we can drop wheezy support (at least for prebuilt images / binaries)

**Comment by jimbo27** [comment]
Test run 1: Installation of Emulationstation, RetroArch (and lr-snes9x-next for testing purpose) from source

Starting environment: Pi2, fresh installed Jessie Lite from 2015-11-21 (kernel 4.1), git and Retropie script installed + all necessary dependencies

Emulationstation: Build - OK (log: http://pastebin.com/q2E3fsnJ), Working - OK
RetroArch: Build - OK (log: http://pastebin.com/SefrQsfJ), Working - OK
lr-snes9x-next: Build - OK (log: http://pastebin.com/xqt8yUhK), Working - OK

Next test run: Installation of Emulationstation, RetroArch from binaries

**Comment by jimbo27** [comment]
Test run 2: Installation of Emulationstation, RetroArch (and lr-snes9x-next for testing purpose) from binaries

Starting environment: Pi2, fresh installed Jessie Lite from 2015-11-21 (kernel 4.1), git and Retropie script installed + all necessary dependencies

Emulationstation: Build - OK (log: http://pastebin.com/WUv3hsdU), Working - NO (error while starting Emulationstation: "error while loading shared libraries: libSM.so.6: cannot open shared object file: No such file or directory")
RetroArch: Build - OK (log: http://pastebin.com/RSnu8zga), Working - ??
lr-snes9x-next: Build - OK (log: http://pastebin.com/BZQWhBBW), Working - ??

Next test run: Retest Installation of Emulationstation, RetroArch from binaries

**Comment by joolswills** [comment]
no idea why it requires libsm - can't see anything in the source as a dependency on that but it must have decided to link with it. However installing libsm-dev would fix it. I don't think when installing from binary we are ever going to get the dependencies 100% if choosing just a couple of packages for reasons like this.

**Comment by joolswills** [comment]
I will dig into this a bit more though - and see if I can find why it links with libSM and as a last resort add it as a dependency.

**Comment by jimbo27** [comment]
Test run 3: Installation ofEmulationstation, RetroArch (and lr-snes9x-next for testing purpose) from binaries, 2nd try

Starting environment: Pi2, fresh installed Jessie Lite from 2015-11-21 (kernel 4.1), git and Retropie script installed + all necessary dependencies, apt-get update & upgrade, get latest of RetroPie script

Emulationstation: Build - OK (log: http://pastebin.com/uWH2zv3b), Working - NO (error while starting Emulationstation: "error while loading shared libraries: libSM.so.6: cannot open shared object file: No such file or directory")
RetroArch: Build - OK (log: http://pastebin.com/8Ev6tN3w), Working - ??
lr-snes9x-next: Build - OK (log: http://pastebin.com/HmKatxhM), Working - ??

Next test run: Install of libsm-dev

**Comment by jimbo27** [comment]
Test run 4: Installation ofEmulationstation, RetroArch (and lr-snes9x-next for testing purpose) from binaries + install if libsm-dev

Starting environment: Result of test run 3

Emulationstation: Build - OK (log: http://pastebin.com/uWH2zv3b), Working - OK
RetroArch: Build - OK (log: http://pastebin.com/8Ev6tN3w), Working - OK
lr-snes9x-next: Build - OK (log: http://pastebin.com/HmKatxhM), Working - OK

Next test run: Installation of all Libretro cores from binaries

**Comment by joolswills** [comment]
if you update retropie-setup i have now included the dependency for ES.

**Comment by zmnpl** [comment]
If that helps:

By chance I just installed RetroPie on Jessie as well. I used binary install, because it was recommended in the README. So far I installed SNES and NES emulation and am using SNES replica controllers. Short test in Emulationstation and SNES emulator seems to be working properly.

Since I just did the fresh install, if there is more stuff I can provide you for debugging or to make you confident about Jessie compatiblity let me know!

**Comment by jimbo27** [comment]
Test run 5: Installation of Emulationstation, RetroArch (and lr-snes9x-next for testing purpose) from binaries

Starting environment: Pi2, fresh installed Jessie Lite from 2015-11-21 (kernel 4.1), git and latest Retropie script installed + all necessary dependencies

Emulationstation: Build - OK (log: http://pastebin.com/j790m8Fx), Working - OK
RetroArch: Build - OK (log: http://pastebin.com/qqKw8jkE), Working - OK
lr-snes9x-next: Build - OK (log: http://pastebin.com/e2naU1Jh), Working - OK

:+1: 

Next test run: Installation of all Libretro cores from binaries

**Comment by ProxyCell** [comment]
are they not able to compile from source right now on jessie?

**Comment by jimbo27** [comment]
@ProxyCell: Not tested yet. I have just build Emulationstation, Retroarch and lr-snes9x-next from source. That worked at least.

**Comment by jimbo27** [comment]
Test run 6: Installation of all Libretro cores (non experimental) from binaries

Starting environment: Pi2, fresh installed Jessie Lite from 2015-11-21 (kernel 4.1), git and Retropie script installed + all necessary dependencies, Emulationstation and Retroarch installed from binaries

lr-armsnes: Build - OK (log: http://pastebin.com/FYdxUee2), Working - OK
lr-bluemsx: Build - OK (log: http://pastebin.com/itWhP3D0), Working - OK
lr-caprice32: Build - OK (log: http://pastebin.com/bLvybf8T), Working - OK
lr-catsfc: Build - OK (log: http://pastebin.com/VdpXLkHd), Working - OK
lr-fba-next: Build - OK (log: http://pastebin.com/Sf8QeHcR), Working - OK
lr-fba: Build - OK (log: http://pastebin.com/aqU24WPD), Working - OK
lr-fceumm: Build - OK (log: http://pastebin.com/MKLpSZaR), Working - OK
lr-fmsx: Build - OK (log: http://pastebin.com/dAaV87Ku), Working - OK
lr-fuse: Build - OK (log: http://pastebin.com/0w4fMx4D), Working - OK
lr-gambatte: Build - OK (log: http://pastebin.com/6eECXPAx), Working - OK
lr-genesis-plus-gx: Build - OK (log: http://pastebin.com/q2inth88), Working - OK
lr-gpsp: Build - OK (log: http://pastebin.com/0xYVd2P1), Working - OK
lr-handy: Build - OK (log: http://pastebin.com/SC3wLgz1), Working - OK
lr-imame4all: Build - OK (log: http://pastebin.com/wU4bNzMY), Working - OK
lr-mame2003: Build - OK (log: http://pastebin.com/f6Ev5czD), Working - OK
lr-mednafen-ngp: Build - OK (log: http://pastebin.com/kX3V6JAe), Working - OK
lr-mednafen-pce-fast: Build - OK (log: http://pastebin.com/pGJYLw6q), Working - OK
lr-mednafen-wswan: Build - OK (log: http://pastebin.com/cGLSy31P), Working - OK
lr-mgba: Build - OK (log: http://pastebin.com/8ZvWc5ZH), Working - OK
lr-mupen64plus: Build - OK (log: http://pastebin.com/D9634Q9p), Working - OK
lr-nestopia: Build - OK (log: http://pastebin.com/ntzqZ72h), Working - OK
lr-nxengine: Build - OK (log: http://pastebin.com/gqT7f8N0), Working - OK
lr-o2em: Build - OK (log: http://pastebin.com/7yTa3cqe), Working - OK
lr-pcsx-rearmed: Build - OK (log: http://pastebin.com/3gtb0vR2), Working - OK
lr-picodrive: Build - OK (log: http://pastebin.com/XDcbj7Mg), Working - OK
lr-pocketsnes: Build - OK (log: http://pastebin.com/Jz97nPxs), Working - OK
lr-ppsspp: Build - OK (log: http://pastebin.com/hL3aChdD), Working - ?? (Couldn't test. I don't have any ISO-File)
lr-prboom: Build - OK (log: http://pastebin.com/wgeAazp0), Working - OK
lr-prosystem: Build - OK (log: http://pastebin.com/Mpzar5qp), Working - OK
lr-snes9x-next: Build - OK (log: http://pastebin.com/Dc1fD5Sg), Working - OK
lr-stella: Build - OK (log: http://pastebin.com/ce1dhPaZ), Working - OK
lr-tgbdual: Build - OK (log: http://pastebin.com/8YhG1P7p), Working - OK
lr-tyrquake: Build - OK (log: http://pastebin.com/76RkHjMN), Working - OK
lr-vba-next: Build - OK (log: http://pastebin.com/AagJ8d6Q), Working - OK
lr-vecx: Build - OK (log: http://pastebin.com/s2CULrtw), Working - OK

Next test run: Installation of all standalone emulators from binaries

**Comment by jimbo27** [comment]
Test run 7: Installation of all standalone emulators from binaries

Starting environment: Pi2, fresh installed Jessie Lite from 2015-11-21 (kernel 4.1), git and Retropie script installed + all necessary dependencies, Emulationstation and Retroarch installed from binaries

advmame: Build - OK (log: http://pastebin.com/0cfTrZTt), Working - OK
atari800: Build - OK (log: http://pastebin.com/25spCvr4), Working - OK
basilisk: Build - OK (log: http://pastebin.com/vshMHXt9), Working - OK
capricerpi: Build - OK (log: http://pastebin.com/XwV97P31), Working - OK
dgen: Build - OK (log: http://pastebin.com/ZpLD0qVc), Working - OK
dosbox: Build - OK (log: http://pastebin.com/n3cAHGMi), Working - OK
fbzx: Build - OK (log: http://pastebin.com/LBPrtGkS), Working - NO (error: "can't load file spectrum-roms/48.rom")
fuse: Build - OK (log: http://pastebin.com/0N078PiT), Working - OK
gngeopi: Build - OK (log: http://pastebin.com/QZ71K8n1), Working - OK
gpsp: Build - OK (log: http://pastebin.com/ncQs3n3c), Working - OK
hatari: Build - OK (log: http://pastebin.com/DQFpyxaa), Working - OK
jzintv: Build - OK (log: http://pastebin.com/GzYFSf9J), Working - OK
linapple: Build - OK (log: http://pastebin.com/pXuWG37n), Working - OK
mame4all: Build - OK (log: http://pastebin.com/vBQymZh0), Working - OK
mupen64plus: Build - OK (log: http://pastebin.com/1q2uq93n), Working - OK
osmose: Build - OK (log: http://pastebin.com/d5sQ4eJ5), Working - OK
pifba: Build - OK (log: http://pastebin.com/tGDis42g), Working - OK
pisnes: Build - OK (log: http://pastebin.com/nH53rc4B), Working - OK
ppsspp: Build - OK (log: http://pastebin.com/ZQaCuPyE), Working - ?? (Couldn't test. I don't have any ISO-File)
reicast: Build - OK (log: http://pastebin.com/8erJQNgr), Working - OK
scummvm: Build - OK (log: http://pastebin.com/psCgHTBG), Working - OK
snes9x: Build - OK (log: http://pastebin.com/NEUKNkBu), Working - OK
uae4all: Build - OK (log: http://pastebin.com/4g7f5dYz), Working - OK
uae4arm: Build - OK (log: http://pastebin.com/FfpHYANh), Working - OK
vice: Build - OK (log: http://pastebin.com/2e4YHinB), Working - OK
xroar: Build - OK (log: http://pastebin.com/eWeUWD4j), Working - OK
ags: Build - OK (log: http://pastebin.com/ZaEGK3En), Working - OK
kodi: Build - OK (log: http://pastebin.com/0LRc8LVx), Working - OK
minecraft: Build - OK (log: http://pastebin.com/zGW0zjVN), Working - OK
openttd: Build - OK (log: http://pastebin.com/7jJQkE0i), Working - OK
supertux: Build - OK (log: http://pastebin.com/vsc6eh4s), Working - OK
limelight: Build - ?? (log: empty log), Working - ?? (Building stuck on searching for Geforce PCs)
scraper: Build - OK (log: http://pastebin.com/wEqGxkdh), Working - OK

Next test run: Installation of all Libretro cores from source

**Comment by joolswills** [comment]
thanks for the feedback. it looks like we got everything. the issues above are not built related as far as I can see - but much appreciated for all the testing.

**Comment by jimbo27** [comment]
You are welcome. :)
Nevertheless I will try to build everything from sources. I'm curious about how this will work out.

**Comment by jimbo27** [comment]
Test run 8: Installation of all Libretro cores from source

Starting environment: Pi2, fresh installed Jessie Lite from 2015-11-21 (kernel 4.1), git and Retropie script installed + all necessary dependencies, Emulationstation and Retroarch installed from binaries

lr-4do: Build - OK (log: http://pastebin.com/GSpHUT9S), Working - OK (superslow)
lr-armsnes: Build - OK (log: http://pastebin.com/ZuMhfSW2), Working - OK
lr-beetle-vb: Build - OK (log: http://pastebin.com/CM6gQ7i9), Working - OK
lr-bluemsx: Build - OK (log: http://pastebin.com/j4KxXBrX), Working - OK
lr-caprice32: Build - OK (log: http://pastebin.com/fmyqtqKC), Working - OK
lr-catsfc: Build - OK (log: http://pastebin.com/pmutqgDZ), Working - OK
lr-desmume: Build - OK (log: http://pastebin.com/J0iwJNyT), Working - OK (superslow)
lr-fba-next: Build - OK (log: https://gist.github.com/jimbo27/6125d90c73a18c49078a), Working - OK
lr-fba: Build - OK (log: http://pastebin.com/9M4dAEhE), Working - OK
lr-fceumm: Build - OK (log: http://pastebin.com/3cqu8vEw), Working - OK
lr-fmsx: Build - OK (log: http://pastebin.com/3cqu8vEw), Working - OK
lr-fuse: Build - OK (log: http://pastebin.com/LkMSb0AF), Working - OK
lr-gambatte: Build - OK (log: http://pastebin.com/D98UkFm5), Working - OK
lr-genesis-plus-gx: Build - OK (log: http://pastebin.com/fAyj5hW8), Working - OK
lr-gpsp: Build - OK (log: http://pastebin.com/D4GqsiWp), Working - OK
lr-gw: Build - OK (log: http://pastebin.com/2ByN36zS), Working - OK
lr-handy: Build - OK (log: http://pastebin.com/XNA9fw1d), Working - OK
lr-imame4all: Build - OK (log: https://gist.github.com/jimbo27/4b1d30de1460a3c34e78), Working - OK
lr-mame2003: Build - OK (log: https://gist.github.com/jimbo27/839d7c397a77cb4e40fd), Working - OK
lr-mame2010: Build - OK (log: https://gist.github.com/jimbo27/0609f3414c9917a3cf88), Working - ?? (I probably don't have proper rom set)
lr-mednafen-ngp: Build - OK (log: http://pastebin.com/EnG0wBJS), Working - OK
lr-mednafen-pce-fast: Build - OK (log: http://pastebin.com/BR1UHfN1), Working - OK
lr-mednafen-wswan: Build - OK (log: http://pastebin.com/z1i4PEkZ), Working - OK
lr-mgba: Build - OK (log: http://pastebin.com/2n1i0Xwf), Working - OK
lr-mupen64plus: Build - OK (log: http://pastebin.com/3uSbCqrr), Working - OK
lr-nestopia: Build - OK (log: http://pastebin.com/Py2h04QG), Working - OK
lr-nxengine: Build - OK (log: http://pastebin.com/mTTXRMe6), Working - OK
lr-o2em: Build - OK (log: http://pastebin.com/1jFsaa1y), Working - OK
lr-pcsx-rearmed: Build - OK (log: http://pastebin.com/cDqHHmNb), Working - OK
lr-picodrive: Build - OK (log: http://pastebin.com/L9rD94tv), Working - NO ( runtime.log: /opt/retropie/emulators/retroarch/bin/retroarch: symbol lookup error: /opt/retropie/libretrocores/lr-picodrive/picodrive_libretro.so: undefined symbol: __aeabi_idiv )
lr-pocketsnes: Build - OK (log: http://pastebin.com/2NQbkaQw), Working - OK
lr-ppsspp: Build - OK (log: http://pastebin.com/7sRPgM6C), Working - OK (choppy)
lr-prboom: Build - OK (log: https://gist.github.com/jimbo27/17e29fd3478873b46121), Working - OK
lr-prosystem: Build - OK (log: http://pastebin.com/jAw69uM1), Working - OK
lr-snes9x-next: Build - OK (log: http://pastebin.com/Lxs1jGVp), Working - OK
lr-stella: Build - OK (log: http://pastebin.com/Zj40iKuP), Working - OK
lr-tgbdual: Build - OK (log: http://pastebin.com/w9Rdu3c3), Working - OK
lr-tyrquake: Build - OK (log: http://pastebin.com/cw0BLMkG), Working - OK
lr-vba-next: Build - OK (log: http://pastebin.com/Je0GvYzJ), Working - OK
lr-vecx: Build - OK (log: http://pastebin.com/GQMLFeTY), Working - OK
lr-virtualjaguar: Build - OK (log: http://pastebin.com/0mSuES16), Working - OK (superslow)
lr-yabause: Build - OK (log:http://pastebin.com/PcF779Db), Working - OK (superslow)

Next test run: Installation of all standalone emulators from source

**Comment by jimbo27** [comment]
Test run 8: Installation of all standalone emulators from source

Starting environment: Pi2, fresh installed Jessie Lite from 2015-11-21 (kernel 4.1), git and Retropie script installed + all necessary dependencies, Emulationstation and Retroarch installed from binaries

advmame: Build - OK (log: https://gist.github.com/jimbo27/6dba778734e657ffc2ba), Working - OK
atari800: Build - OK (log: http://pastebin.com/K2YVWLYz), Working - OK
basilisk: Build - OK (log: http://pastebin.com/A5ghxesa), Working - OK
capricerpi: Build - NO (log: http://pastebin.com/JUaWd7Uj), Working - OK
dgen: Build - OK (log: http://pastebin.com/UPCjRpAe), Working - OK
dosbox: Build - OK (log: http://pastebin.com/Jiaz67jt), Working - OK
fbzx: Build - OK (log: http://pastebin.com/Jiaz67jt), Working - NO (missing bios file 48.rom)
fuse: Build - OK (log: http://pastebin.com/5hPGNRqb), Working - OK
gngeopi: Build - OK (log: http://pastebin.com/BrW7Zwrs), Working - OK
gpsp: Build - OK (log: http://pastebin.com/PQ4NXi7z), Working - OK
hatari: Build - OK (log: http://pastebin.com/UpNByNvY), Working - OK
jzintv: Build - OK (log: http://pastebin.com/Yrj8TREY), Working - OK
linapple: Build - OK (log: http://pastebin.com/uaCaTHUf), Working - OK
mame4all: Build - OK (log: https://gist.github.com/jimbo27/887de96a67d7f9c21247), Working - OK
mupen64plus: Build - OK (log: http://pastebin.com/rwk5aSJn), Working - OK
osmose: Build - OK (log: http://pastebin.com/LvNWcGdN), Working - OK
pifba: Build - OK (log: http://pastebin.com/T5Tq8Hsz), Working - OK
pisnes: Build - OK (log: http://pastebin.com/sGjN1LZD), Working - OK
ppsspp: Build - OK (log: http://pastebin.com/xddnN73X), Working - OK
reicast: Build - OK (log: http://pastebin.com/vfLXqey5), Working - OK
scummvm: Build - OK (log: http://pastebin.com/QkUgbJdY), Working - OK
snes9x: Build - OK (log: http://pastebin.com/y4TjfQ54), Working - OK
uae4all: Build - OK (log: http://pastebin.com/0rJCGGhF), Working - OK
uae4arm: Build - OK (log: http://pastebin.com/HKn0Hj5i), Working - OK
vice: Build - OK (log: https://gist.github.com/jimbo27/99d63bb1a5888327de54), Working - OK
xroar: Build - OK (log: http://pastebin.com/XmT7D65H), Working - OK
eduke32: Build - OK (log: http://pastebin.com/ii5VLFN8), Working - OK
quake3: Build - OK (log: http://pastebin.com/TUPsyrUT), Working - OK
smw: Build - OK (log: http://pastebin.com/8X1sTSvJ), Working - OK
ags: Build - NO (log: http://pastebin.com/iYef7F0U), Working - OK
openmsx: Build - OK (log: http://pastebin.com/Kkadjr0e), Working - OK
pcsx-rearmed: Build - OK (log: http://pastebin.com/hiiRV6NZ), Working - OK
px68k: Build - OK (log: http://pastebin.com/d8qTSUGy), Working - NO (bios missing?)
zesarux: Build - OK (log: http://pastebin.com/g2kdhYMC), Working - OK
dxx-rebirth: Build - OK (log: http://pastebin.com/4SJVumY7), Working - OK
opentyrian: Build - OK (log: http://pastebin.com/VnVeeKRq), Working - OK
wolf4sdl: Build - OK (log: http://pastebin.com/PB2PT0rH), Working - OK
zdoom: Build - NO (log: http://pastebin.com/uHi5QZpV), Working - OK
virtualgamepad: Build - OK (log: http://pastebin.com/t11ePGw4), Working - ?? (Don't know how to test)

That's it. All tests done.

**Comment by joolswills** [comment]
Thanks.

fbzx and zdoom should be fixed now. px68k needs a few bios files but it does work.

**Comment by joolswills** [comment]
ags should be sorted now too.

**Comment by ProxyCell** [comment]
so for LR only lr-picodrive is not compiling from source on Jessie and lr-mame2010 may not have been tested - these are actually very encouraging results

i will test everything you listed as poorly performing/slow as well as lr-mame2012 and lr-picodrive
will use jessie lite as well as the full jessie just in case

**Comment by joolswills** [comment]
picodrive compiles fine. there was a problem above running it but it works on my set up from my last build - I will be checking it of course in case there is a regression.

At this stage we don't need any more testing - but thanks for the offer.

**Comment by joolswills** [comment]
Closing as Jessie is now our official version. Thanks for all the help everyone.

**Comment by KitchUK** [comment]
Lr picordive seems to be having the symbol lookup error again. I just built form source.

**Comment by joolswills** [comment]
please open a new ticket, providing details of setup / versions etc/

**Comment by zgoda** [comment]
Sorry for reviving old thread but this is the only reference for `_to16Bit` symbol missing I could find. This is really a question to @joolswills as I see only "mgba issue fixed" message here - how it was resolved? I have now the exact same error with mGBA core on another ARMv7 platform (Debian Jessie based).
