### ISSUE TITLE
Random freezing when using bluetooth ps3 controllers on pi 3 Retropie 3.7

### ISSUE THREAD

**Issue by tommydills** [RetroPie/RetroPie-Setup#1449]
I'm having some frequent freezing issues with emulationstation, only when I'm using bluetooth controllers.  Sometimes it is in game, sometimes when exiting a game, and sometimes when starting a game.  I am using the onboard bluetooth, and unfortunately I do not have a dongle to try instead of the onboard.  Last night it probably happened about 5 times in 2 hours, and I am usually unable to ssh into the machine, but if i do it wont follow through with the shutdown command.

**Comment by joolswills** [comment]
Known hardware/driver issue - https://github.com/raspberrypi/linux/issues/1360 - there are multiple threads about this on the forum also.

**Comment by joolswills** [comment]
The solution currently is to use an additional bluetooth dongle.

**Comment by tommydills** [comment]
whoops, i looked for it but must have missed it.  Thanks.

**Comment by joolswills** [comment]
It's ok to leave this open for now - will hopefully aid with people looking for the problem. cheers.

**Comment by dcs619** [comment]
+1 same issue

**Comment by rajder** [comment]
+1

**Comment by oguzhan1907** [comment]
+1 same same

**Comment by joolswills** [comment]
I'm not sure there is any benefit doing a +1 - it is a known issue that affects all PI3 users. Adding +1 will not help it be fixed any quicker.

**Comment by HerbFargus** [comment]
Also to mention there are emoticon +1 things that you can put on the original post without spamming the thread

**Comment by rajder** [comment]
Sorry for the spam, just showing my interest in this issue to get notifications on updates. :)

**Comment by eddywebs** [comment]
+1 issue with pi3 crashing with onboard bluetooth and ps3 controllers, is there any status updated on this ?

**Comment by joolswills** [comment]
Follow the earlier link (which would be clearer if everyone wasn't adding +1 posts which don't help)

**Comment by dankcushions** [comment]
looks like this might be fixed in kernel 4.4 https://github.com/raspberrypi/linux/issues/1360#issuecomment-217863895 (and later updates)

**Comment by konradsa** [comment]
It's pretty much confirmed now that this bug has been fixed in kernel 4.4. To the Retropie devs: Please update Retropie to a newer kernel version so that everybody can get the benefit. Based on reports from [https://github.com/raspberrypi/linux/issues/1360](https://github.com/raspberrypi/linux/issues/1360), kernel 4.4 works without a problem with Retropie 3.7. This post also has instructions on how to upgrade  the kernel manually for everybody here that wants to try out the fix.

**Comment by joolswills** [comment]
RetroPie is not a not a distro - our image is just RetroPie install on top of Raspbian. So when Raspbian update the packaged kernel, our next image will contain it.

**Comment by konradsa** [comment]
Looks like this just happened actually:
https://www.raspberrypi.org/blog/another-update-raspbian/

**Comment by eddywebs** [comment]
There are no more crashes after updating to linux kernel to 4.4 >> https://github.com/raspberrypi/linux/issues/1360#issuecomment-217863895

However any additional controller still fail to pair on retropie, this time there is no bluetooth crash its just no paring as 2nd or 3d controller.

**Comment by RetroPieNerd** [comment]
You can close this issue now...

I have updated the Bluetooth page: https://github.com/RetroPie/RetroPie-Setup/wiki/Setting-up-a-Bluetooth-controller
